name: let_me_cook
description: "A recipe app"
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  path_provider: ^2.0.10
  dropdown_search: ^5.0.3
  share_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/images/app_icon.png"

flutter:
  assets:
    - assets/images/placeholder.png
  uses-material-design: true